---
- hosts: testhost
  tasks:
    - copy: src=test1.xml dest=/root/test1.xml
    - copy: src=test1.xml dest=/root/test1_1.xml
    - modify_xml:
        file: /root/test1_1.xml
        selector: country
        value_str: <testtag>1</testtag>
        value_tag: jkdsafd
        action: replace
#    - copy: src=test1.xml dest=/root/test1_2.xml
#    - modify_xml:
#    - copy: src=test1.xml dest=/root/test1_3.xml
#    - modify_xml:
